# Docker-compose.yml con MySQL 8.0 y Redis 7.0.5

version: '3'

services:

  redis-gosf:
    image: redis:${REDIS_TAG:-7.0.5}
    container_name: redis-gosf
    # ports:
    #   - "6379:6379"
    # volumes:
    #   - ${VOLUME_PATH}/redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: always
  
  mysql-gosf:
    image: mysql:${MYSQL_TAG:-8.0-debian}
    container_name: mysql-gosf
    command: --default-authentication-plugin=mysql_native_password
    # ports:
      # - "3306:3306"
    # volumes:
    #   - ${VOLUME_PATH}/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "gosf"
      MYSQL_USER: "gosf"
      MYSQL_PASSWORD: "gosf"
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SHOW TABLES;'"
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: always

  app-gosf:
    container_name: app-gosf
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./config-gosf.env
    ports:
      - "${GOSF_PORT:-3000}:80" 
    depends_on:
      mysql-gosf:
        condition: service_healthy
      redis-gosf:
        condition: service_healthy
    # volumes:
      # - ${VOLUME_PATH}/files:/app/files
      # - ${VOLUME_PATH}/static:/app/static
    restart: always
